export const venues = [
  // IT Block Events
  { eventName: 'Blind Coding', venue: 'UG III', floor: 'First Floor', department: 'IT Block' },
  { eventName: 'SQL Treasure Hunt', venue: 'UG I', floor: 'Ground Floor', department: 'IT Block' },
  { eventName: 'Tech Quest (Technical Quiz)', venue: 'Seminar Hall', floor: 'Second Floor', department: 'IT Block' },
  { eventName: 'Code Relay', venue: 'UG III', floor: 'First Floor', department: 'IT Block' },
  { eventName: 'Bug Bash (Code Debugging)', venue: 'UG II', floor: 'Ground Floor', department: 'IT Block' },
  { eventName: 'Stack & Run', venue: 'Seminar Hall', floor: 'Second Floor', department: 'IT Block' },
  { eventName: 'Floating Balls', venue: 'Seminar Hall', floor: 'Second Floor', department: 'IT Block' },
  { eventName: 'Oracle APEX', venue: 'Seminar Hall', floor: 'Second Floor', department: 'IT Block' },
  { eventName: 'Mastering Advanced PL-SQL', venue: 'UG I', floor: 'Ground Floor', department: 'IT Block' },
  { eventName: 'Machine Learning Made Easy', venue: 'Smart Classroom', floor: 'First Floor', department: 'IT Block' },
  { eventName: 'Paper Presentation', venue: 'Smart Classroom 2', floor: 'First Floor', department: 'IT Block' },
  { eventName: "Creator's Spark", venue: 'UG II', floor: 'Ground Floor', department: 'IT Block' },
  { eventName: 'DIG THE BUG (Code Debugging)', venue: 'UG I', floor: 'Ground Floor', department: 'IT Block' },
  { eventName: 'CSS BATTLE', venue: 'UG I', floor: 'Ground Floor', department: 'IT Block' },
  { eventName: 'Picture Pursuit', venue: 'LH-3', floor: 'Ground Floor', department: 'IT Block' },
  { eventName: 'Lost In Lyrics', venue: 'IT', floor: 'Unknown', department: 'IT Block' },

  // CSE Block Events
  { eventName: 'Incognito Code', venue: 'ICL Lab', floor: 'Ground Floor', department: 'CSE Block' },
  { eventName: 'Paper Presentation', venue: 'APJ Lab , CVR Lab , F7 , F12', floor: 'Ground Floor, First Floor', department: 'CSE Block' },
  { eventName: 'War of UI/UX', venue: 'CISCO Lab, RM Lab', floor: 'Ground Floor', department: 'CSE Block' },
  { eventName: 'Tech Quiz Face-Off', venue: 'CISCO Lab', floor: 'Ground Floor', department: 'CSE Block' },
  { eventName: 'Code Cool', venue: 'ICL Lab, IBM Lab', floor: 'Ground Floor', department: 'CSE Block' },
  { eventName: 'Prompt Engineering', venue: 'CISCO Lab, RM Lab', floor: 'Ground Floor', department: 'CSE Block' },
  { eventName: 'Entrepreneurial Conclave', venue: 'Seminar Hall', floor: 'Second Floor', department: 'CSE Block' },
  { eventName: 'Capture the Flag', venue: 'Activity Hall', floor: 'Second Floor', department: 'CSE Block' },
  { eventName: 'Freeze the Frame', venue: 'S6', floor: 'Second Floor', department: 'CSE Block' },
  { eventName: 'Cine Quiz', venue: 'Seminar Hall', floor: 'Second Floor', department: 'CSE Block' },
  { eventName: 'Meme Forge', venue: 'APJ Lab, CVR Lab', floor: 'Ground Floor', department: 'CSE Block' },
  { eventName: 'Best Manager', venue: 'F14', floor: 'First Floor', department: 'CSE Block' },
  { eventName: 'On Spot Sketch', venue: 'S6', floor: 'Second Floor', department: 'CSE Block' },
  { eventName: 'Creating Design with AR Development', venue: 'Seminar Hall', floor: 'Second Floor', department: 'CSE Block' },
  { eventName: 'Linux Workshop', venue: 'ICL Lab', floor: 'Ground Floor', department: 'CSE Block' },
  { eventName: 'Next-Gen Learning', venue: 'ICL Lab', floor: 'Ground Floor', department: 'CSE Block' },
  { eventName: 'Role of geo spatial and IOT', venue: 'F14', floor: 'First Floor', department: 'CSE Block' },

  // Mechanical Block Events
  { eventName: 'Paper Presentation', venue: 'Seminar Hall', floor: 'Ground Floor', department: 'Mechanical Block' },
  { eventName: 'Design-O-Mania', venue: 'CAD Lab', floor: 'Ground Floor', department: 'Mechanical Block' },
  { eventName: 'Mr. TALENT', venue: 'Seminar Hall', floor: 'Ground Floor', department: 'Mechanical Block' },
  { eventName: 'Techno Chill', venue: 'Smart Classroom', floor: 'Ground Floor', department: 'Mechanical Block' },
  { eventName: 'Mech Connection', venue: 'Smart Classroom', floor: 'Ground Floor', department: 'Mechanical Block' },
  { eventName: 'Mr. Assembler', venue: 'Workshop', floor: 'Unknown', department: 'Mechanical Block' },
  { eventName: 'AI Art & Meme Contest', venue: 'Seminar Hall', floor: 'Ground Floor', department: 'Mechanical Block' },
  { eventName: 'Miniature Roller Coaster Design Challenge', venue: 'Smart Classroom', floor: 'Ground Floor', department: 'Mechanical Block' },
  { eventName: 'Scavenger Hunt', venue: 'Laboratories', floor: 'Unknown', department: 'Mechanical Block' },
  { eventName: 'Rocket Launch Contest', venue: 'Play Ground', floor: 'Unknown', department: 'Mechanical Block' },
  { eventName: 'Industrial Geometric Dimensioning and Tolerancing', venue: '', floor: 'Unknown', department: 'Mechanical Block' },

  // ECE Block Events
  { eventName: 'Fusion Frenzy', venue: 'Embedded Lab', floor: 'Ground Floor', department: 'ECE Block' },
  { eventName: 'Decryptathon', venue: 'Networks Lab', floor: 'Ground Floor', department: 'ECE Block' },
  { eventName: 'Circuit Debugging', venue: 'ED Lab', floor: 'Unknown', department: 'ECE Block' },
  { eventName: 'EmbedX', venue: 'Vlsi Lab', floor: 'First Floor', department: 'ECE Block' },
  { eventName: 'Paper Presentation', venue: 'H12 Smart class Room', floor: 'Unknown', department: 'ECE Block' },
  { eventName: 'ElectroVision', venue: 'Smart Classroom', floor: 'First Floor', department: 'ECE Block' },
  { eventName: 'Linkage', venue: 'H21 Classroom', floor: 'Second Floor', department: 'ECE Block' },
  { eventName: 'Wave Wire', venue: 'DSP Lab', floor: 'Second Floor', department: 'ECE Block' },
  { eventName: 'Tech Detective', venue: 'ECE', floor: 'Unknown', department: 'ECE Block' },
  { eventName: 'Crystal Pixel', venue: 'DSP Lab', floor: 'Second Floor', department: 'ECE Block' },
  { eventName: 'Filmora', venue: 'DSP Lab', floor: 'Second Floor', department: 'ECE Block' },
  { eventName: 'Shake up the fun', venue: 'Seminar Hall', floor: 'Second Floor', department: 'ECE Block' },
  { eventName: 'Exquiz me', venue: 'Smart Class Room', floor: 'First Floor', department: 'ECE Block' },
  { eventName: 'Tamizhodu Vilayaadu', venue: 'Seminar Hall', floor: 'Second Floor', department: 'ECE Block' },
  { eventName: 'Antenna Design and Fabrication', venue: 'Embedded Lab', floor: 'Ground Floor', department: 'ECE Block' },
  { eventName: 'Embedded System Design With Arm Processor', venue: 'Embedded Lab', floor: 'Ground Floor', department: 'ECE Block' },
  { eventName: 'Smart Wireless Sensor Networks In Iot Applications', venue: 'Networks Lab', floor: 'Ground Floor', department: 'ECE Block' },
  { eventName: 'Software Defined Radio using USRP & LabVIEW', venue: 'DSP Lab', floor: 'Second Floor', department: 'ECE Block' },

  // EEE Block Events
  { eventName: 'Paper Presentation', venue: 'Seminar Hall', floor: 'Second Floor', department: 'EEE Block' },
  { eventName: 'Technical Quiz', venue: 'Active Classroom', floor: 'Second Floor', department: 'EEE Block' },
  { eventName: 'Project Expo', venue: 'Power Electronics Lab', floor: 'Ground Floor', department: 'EEE Block' },
  { eventName: 'Circuit Debugging', venue: 'Electrical Workshop Lab', floor: 'Ground Floor', department: 'EEE Block' },
  { eventName: 'Coding Contest', venue: 'New Computer Lab - EEE', floor: 'Ground Floor', department: 'EEE Block' },
  { eventName: 'Tech Encrypt', venue: 'H2 Classroom', floor: 'First Floor', department: 'EEE Block' },
  { eventName: 'Loggic Ladder', venue: 'Electronics Lab', floor: 'First Floor', department: 'EEE Block' },
  { eventName: 'Poster Design', venue: 'H3 Classroom', floor: 'First Floor', department: 'EEE Block' },
  { eventName: 'Cup Bridge', venue: 'Active Classroom', floor: 'Second Floor', department: 'EEE Block' },
  { eventName: 'Walker Bottle', venue: 'Seminar Hall', floor: 'Second Floor', department: 'EEE Block' },
  { eventName: 'Guess the Beat', venue: 'H5 Classroom', floor: 'First Floor', department: 'EEE Block' },
  { eventName: 'Capture & Remember', venue: 'Seminar Hall', floor: 'Second Floor', department: 'EEE Block' },
  { eventName: 'Fast and Frolic', venue: 'Active Classroom', floor: 'Second Floor', department: 'EEE Block' },
  { eventName: 'Embedded Systems with Arduino: IoT Applications', venue: 'EEE', floor: 'Unknown', department: 'EEE Block' },
  { eventName: 'High Voltage Insulator Flashover Analysis', venue: 'EEE', floor: 'Unknown', department: 'EEE Block' },
  { eventName: 'Numerical Relays', venue: 'EEE', floor: 'Unknown', department: 'EEE Block' },
  { eventName: 'Battery Management Systems (BMS) Workshop', venue: 'EEE', floor: 'Unknown', department: 'EEE Block' },
  { eventName: 'Robotics and Automation Workshop', venue: 'EEE', floor: 'Unknown', department: 'EEE Block' },

  // AIDS Block Events
  { eventName: 'Devfest', venue: 'Data Analytics Lab', floor: 'Ground Floor', department: 'AIDS Block' },
  { eventName: 'AI Builders Sprint', venue: 'AI Lab', floor: 'Ground Floor', department: 'AIDS Block' },
  { eventName: 'Unfold Chronicles of Data', venue: 'Deep Learning Lab', floor: 'Ground Floor', department: 'AIDS Block' },
  { eventName: 'AI Product Demo', venue: 'Lecture Hall', floor: 'First Floor', department: 'AIDS Block' },
  { eventName: 'AI Thought Craft', venue: 'AI Lab', floor: 'Ground Floor', department: 'AIDS Block' },
  { eventName: 'Listen and Identify', venue: 'AI Lab', floor: 'Ground Floor', department: 'AIDS Block' },
  { eventName: 'Connexion', venue: 'Seminar Hall', floor: 'First Floor', department: 'AIDS Block' },
  { eventName: 'Act and React', venue: 'Seminar Hall', floor: 'First Floor', department: 'AIDS Block' },
  { eventName: 'Adventure Hunt', venue: 'AI Lab', floor: 'Ground Floor', department: 'AIDS Block' },
  { eventName: 'AI Powered Edge Intelligence', venue: 'Deep Learning Lab', floor: 'Ground Floor', department: 'AIDS Block' },
  { eventName: 'Agentic AI', venue: 'AI Lab', floor: 'Ground Floor', department: 'AIDS Block' },
  { eventName: 'GenAI for web solutions', venue: 'AI Lab', floor: 'Ground Floor', department: 'AIDS Block' },

  // Civil Block Events
  { eventName: 'Code Twist', venue: 'Smart Classroom', floor: 'First Floor', department: 'Civil Block' },
  { eventName: 'Paper Presentation', venue: 'Seminar Hall', floor: 'First Floor', department: 'Civil Block' },
  { eventName: 'Cad Modeling', venue: 'CAD Lab', floor: 'Ground Floor', department: 'Civil Block' },
  { eventName: 'Build Battle', venue: 'CAD Lab', floor: 'Ground Floor', department: 'Civil Block' },
  { eventName: 'Quote or Quit', venue: 'Seminar Hall', floor: 'First Floor', department: 'Civil Block' },
  { eventName: 'Word Debate', venue: 'Smart Classroom', floor: 'First Floor', department: 'Civil Block' },
  { eventName: 'Tech Pirates', venue: 'Survey Lab', floor: 'First Floor', department: 'Civil Block' },
  { eventName: 'Triwizard Truss', venue: 'Soil Lab', floor: 'Ground Floor', department: 'Civil Block' },
  { eventName: 'Team Tango', venue: 'LH3', floor: 'First Floor', department: 'Civil Block' },
  { eventName: 'BIM in Civil Engineering', venue: 'CAD Lab', floor: 'Ground Floor', department: 'Civil Block' },
  { eventName: 'AI Applications in Civil Engineering', venue: 'CAD Lab', floor: 'Ground Floor', department: 'Civil Block' },
  { eventName: 'Standard Penetration Test', venue: 'Data Analytics Lab', floor: 'Ground Floor', department: 'Civil Block' },

  // S&H Block Events
  { eventName: 'Poster Presentation', venue: 'Drawing Hall', floor: 'Second Floor', department: 'S&H Block' },
  { eventName: 'TECHNO SPARK', venue: 'Seminar Hall', floor: 'First Floor', department: 'S&H Block' },
  { eventName: 'Paper Presentation', venue: 'LH3', floor: 'Ground Floor', department: 'S&H Block' },
  { eventName: 'Tech Meets Text', venue: 'English Lab', floor: 'Second Floor', department: 'S&H Block' },
  { eventName: 'Litsphere', venue: 'Seminar Hall', floor: 'First Floor', department: 'S&H Block' },
  { eventName: 'Mathletics', venue: 'Seminar Hall', floor: 'First Floor', department: 'S&H Block' },
  { eventName: 'Cerebral Event', venue: 'Seminar Hall', floor: 'First Floor', department: 'S&H Block' },
  { eventName: 'Fusion Frontiers', venue: 'LH2 and LH3', floor: 'Ground Floor', department: 'S&H Block' },
  { eventName: 'Elevate your Mind', venue: 'Smart class Room', floor: 'Ground Floor', department: 'S&H Block' },
  { eventName: 'Circuit Symphony: Crafting Electronics', venue: 'English Lab', floor: 'Second Floor', department: 'S&H Block' },
  { eventName: 'Master Your Mic', venue: 'Seminar hall', floor: 'First Floor', department: 'S&H Block' },
  { eventName: 'Ecoche Insights-Instrumental Techniques for Environmental', venue: 'Chemistry research centre', floor: 'Unknown', department: 'S&H Block' },
  { eventName: 'The Essential Mathematics behind Engineering Breakthrough', venue: 'Smart Classroom', floor: 'Ground Floor', department: 'S&H Block' }
];